-- CREAZIONE TABELLA: PREFERITI
CREATE TABLE IF NOT EXISTS PREFERITI_IMMOBILI (
    id INTEGER AUTO_INCREMENT,
    id_utente INTEGER,
    id_immobile INTEGER,
    PRIMARY KEY(id),
    FOREIGN KEY(id_utente) REFERENCES UTENTI(id) ON UPDATE CASCADE,
    FOREIGN KEY(id_immobile) REFERENCES IMMOBILI(id) ON UPDATE CASCADE
) ENGINE = InnoDB;
