-- CREAZIONE TABELLA: TIPOLOGIE_ALLOGGIO
CREATE TABLE IF NOT EXISTS TIPOLOGIE_ALLOGGIO(
    id INTEGER AUTO_INCREMENT,
    immagine VARCHAR(255) NOT NULL,
    alt VARCHAR(255) NOT NULL,
    tipologia VARCHAR(255) NOT NULL,   
    PRIMARY KEY(id)
) Engine = 'InnoDB';

-- DATI PER TABELLA: TIPOLOGIE_ALLOGGIO
INSERT INTO TIPOLOGIE_ALLOGGIO (immagine, alt, tipologia) VALUES
('logo_sull_acqua.jpg', 'Sull\'acqua', 'Sull\'acqua'),
('logo_piscine_incredibili.jpg', 'Piscine incredibili', 'Piscine incredibili'),
('logo_vista_mozzafiato.jpg', 'Vista mozzafiato', 'Vista mozzafiato'),
('logo_spazi_creativi.jpg', 'Spazi creativi', 'Spazi creativi'),
('logo_mulini.jpg', 'Mulini', 'Mulini'),
('logo_wow.jpg', 'Wow!', 'Wow!'),
('logo_baite.jpg', 'Baite', 'Baite'),
('logo_case_sull_albero.jpg', 'Case sull\'albero', 'Case sull\'albero'),
('logo_agriturismi.jpg', 'Agriturismi', 'Agriturismi'),
('logo_castelli.jpg', 'Castelli', 'Castelli'),
('logo_campagna.jpg', 'Campagna', 'Campagna'),
('logo_design.jpg', 'Design', 'Design'),
('logo_parchi_nazionali.jpg', 'Parchi nazionali', 'Parchi nazionali'),
('logo_minicase.jpg', 'Minicase', 'Minicase'),
('logo_luxe.jpg', 'Luxe', 'Luxe'),
('logo_dimore_storiche.jpg', 'Dimore storiche', 'Dimore storiche'),
('logo_luoghi_remoti.jpg', 'Luoghi remoti', 'Luoghi remoti'),
('logo_lago.jpg', 'Lago', 'Lago'),
('logo_di_tendenza.jpg', 'Di tendenza', 'Di tendenza'),
('logo_trulli.jpg', 'Trulli', 'Trulli'),
('logo_barche.jpg', 'Barche', 'Barche'),
('logo_camping.jpg', 'Camping', 'Camping'),
('logo_fronte_lago.jpg', 'Fronte lago', 'Fronte lago'),
('logo_vigneti.jpg', 'Vigneti', 'Vigneti'),
('logo_isole.jpg', 'Isole', 'Isole'),
('logo_case_organiche.jpg', 'Case organiche', 'Case organiche'),
('logo_ville.jpg', 'Ville', 'Ville'),
('logo_grotte.jpg', 'Grotte', 'Grotte'),
('logo_B&B.jpg', 'B&B', 'B&B'),
('logo_cupole.jpg', 'Cupole', 'Cupole'),
('logo_dammusi.jpg', 'Dammusi', 'Dammusi'),
('logo_tropicali.jpg', 'Tropicali', 'Tropicali'),
('logo_novita.jpg', 'Novità', 'Novità'),
('logo_case_galleggianti.jpg', 'Case galleggianti', 'Case galleggianti'),
('logo_iurte.jpg', 'Iurte', 'Iurte'),
('logo_fienili.jpg', 'Fienili', 'Fienili'),
('logo_pianoforti_a_coda.jpg', 'Pianoforti a coda', 'Pianoforti a coda'),
('logo_torri.jpg', 'Torri', 'Torri'),
('logo_citta_popolari.jpg', 'Città popolari', 'Città popolari'),
('logo_surf.jpg', 'Surf', 'Surf'),
('logo_spazi_per_giocare.jpg', 'Spazi per giocare', 'Spazi per giocare'),
('logo_polo_nord.jpg', 'Polo nord', 'Polo nord'),
('logo_container.jpg', 'Container', 'Container'),
('logo_ryokan.jpg', 'Ryokan', 'Ryokan'),
('logo_in_cima_al_mondo.jpg', 'In cima al mondo', 'In cima al mondo'),
('logo_cucine_professionali.jpg', 'Cucine professionali', 'Cucine professionali'),
('logo_stanze.jpg', 'Stanze', 'Stanze'),
('logo_riad.jpg', 'Riad', 'Riad'),
('logo_case_cicladiche.jpg', 'Case cicladiche', 'Case cicladiche'),
('logo_a-frame.jpg', 'A-Frame', 'A-Frame'),
('logo_capanne.jpg', 'Capanne', 'Capanne'),
('logo_casas_particulares.jpg', 'Casas particuleres', 'Casas particuleres'),
('logo_sulle_piste.jpg', 'Sulle piste', 'Sulle piste'),
('logo_golf.jpg', 'Golf', 'Golf'),
('logo_hanok.jpg', 'Hanok', 'Hanok'),
('logo_sci.jpg', 'Sci', 'Sci'),
('logo_nel_deserto.jpg', 'Nel deserto', 'Nel deserto'),
('logo_minsu.jpg', 'Minsu', 'Minsu'),
('logo_camper.jpg', 'Camper', 'Camper'),
('logo_spazi_accessibili.jpg', 'Spazi accessibili', 'Spazi accessibili'),
('logo_spiaggia.jpg', 'Spiaggia', 'Spiaggia');





