-- CREAZIONE TABELLA UTENTI
CREATE TABLE IF NOT EXISTS UTENTI (
    id INTEGER AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    nome VARCHAR(50) NOT NULL,
    cognome VARCHAR(50) NOT NULL,
    data_di_nascita DATE NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

  

 

